### ISSUE TITLE
Any chance to update for hcl connections?

### ISSUE THREAD

**Issue by johanmpoot** [benkroeger/passport-ibm-connections-cloud#2]
e.g. instead of '/manage/oauth2/authorize' you should use:
  '/auth/realms/connections-mt/protocol/openid-connect/auth';
 
you can obtain tokens from:
  '/auth/realms/connections-mt/protocol/openid-connect/token';
 
and validate a token by requesting a user from:
  '/auth/realms/connections-mt/protocol/openid-connect/userinfo';

**Comment by benkroeger** [comment]
nope - but take a look at [passport-oidc](https://github.com/benkroeger/passport-oidc) I know it lacks documentation and hasn't been updated for a while - but it should support what you're looking for
